Repository sendsmaily/smaily-magento-extension, pull requests merged in 2021-10, with the labels that each got.

#66 Add Visual Studio Code settings for sandbox environment
  .github/workflows/release.yaml
  .vscode/settings.json
Labels: maintenance

#70 Release 2.2.0 checklist changes
  CHANGELOG.md
  README.md
  assets/newsletter_subscription_form.png
  composer.json
  etc/module.xml
Labels: release

#71 Update user manual links
  README.md
  USERGUIDE.md
Labels: documentation, maintenance
